version: "3.3"
services:
  tailscale:
      hostname: tailscale                                          # This will become the tailscale device name
      container_name: tailscale
      image: tailscale/tailscale:latest
      network_mode: host
      volumes:
          - /portainer/Files/AppData/Config/tailscale:/var/lib        # State data will be stored in this directory
          - /dev/net/tun:/dev/net/tun                      # Required for tailscale to work
      cap_add:                                             # Required for tailscale to work
        - net_admin
        - sys_module
      command: tailscaled
      restart: unless-stopped



#version: "3.3"
#services:
#    netbird:
#        container_name: netbird
#        hostname: PEER_NAME # This will become the netbird device name
#        cap_add:
#            - NET_ADMIN
#            - SYS_ADMIN
#            - SYS_RESOURCE
#        environment:
#            - NB_SETUP_KEY=key
#        image: netbirdio/netbird:latest
